### PR TITLE
Enhancement of Licence.md file.

### PR DESCRIPTION
**Pull request by Saharshjain78**
# Prerequisites
Before submitting an issue, please ensure the following:

- [x] I have completed the assigned task.
- [x] I am certain that I have fulfilled the task's requirements.
- [x] I have confidence that the code is functioning as expected.
- [x] It is at a stage where it can be deployed to production.

# How to Test the Pull Request (PR)

(you can review the `licence.md` file)

# Issue

Issue #41

# Screenshots

I will attach the necessary files.

Screenshot 2023-10-23 163218

### CODE REVIEW

**Comment by Saharshjain78** [comment]
Hey Richard and Danial, I wanted to know about the progress of the PR, and let me know if there are some changes.

**Comment by danielmarv** [comment]
Please if you r making the PRs tag the reviewers

**Review by Saharshjain78 — COMMENTED** [review]
Since the software will consist of patents, these changes are essential

**Comment by Saharshjain78** [comment]
@danielmarv Can you please guide me on why the Vercel check has been cancelled?

**Review by Saharshjain78 — COMMENTED** [review]
These changes are necessary as the product contains the patents.

**Comment by Saharshjain78** [comment]
@danielmarv @Rhonitah @TroyMoses @AgrichubAdmin  I have created another pr with all the checks that got passed without any conflicts.

**Pull request closed without merging**
